#!/usr/bin/env bash
# ==============================================================================
# Copyright (c) 2026 Coding Kinetics LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

set -euo pipefail

# ==============================================================================
# STEP 1: PRE-CAPTURE CHECKS & PERMISSIONS
# ==============================================================================
# - Ensure device is attached and authorized via ADB.
# - The target app package must match 'atrace_apps' below (must be debuggable or
#   profileable in production builds).
APP_PACKAGE="com.example.yourapp"
TRACE_OUTPUT_DEVICE="/data/misc/perfetto-traces/trace.perfetto-trace"
TRACE_OUTPUT_HOST="./trace.perfetto-trace"

echo "[*] Verifying ADB connection..."
adb get-state > /dev/null 2>&1 || { echo "[-] Error: No ADB device connected"; exit 1; }

# ==============================================================================
# STEP 2: RUN ON-DEVICE PERFETTO TRACE CAPTURE VIA ADB
# ==============================================================================
# - Duration: 10,000 ms (10 seconds)
# - Captures Android platform atrace markers (am, view, sched) and CPU slices
# - Scopes application-level tracing sections (androidx.tracing) to the specified app
echo "[*] Triggering Perfetto capture on device for 10 seconds..."
echo "[*] Interact with ${APP_PACKAGE} now to reproduce target behavior..."

adb shell perfetto \
  -c - --txt \
  -o "${TRACE_OUTPUT_DEVICE}" <<EOF
buffers: {
    size_kb: 65536
    fill_policy: RING_BUFFER
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            # Kernel scheduler context switches & CPU clock scaling
            ftrace_events: "sched_switch"
            ftrace_events: "power/cpu_frequency"

            # Android platform tracing categories
            atrace_categories: "am"
            atrace_categories: "view"
            atrace_categories: "sched"

            # App package targeted for androidx.tracing / Trace.beginSection()
            atrace_apps: "${APP_PACKAGE}"
        }
    }
}
duration_ms: 10000
EOF

# ==============================================================================
# STEP 3: PULL TRACE ARTIFACT TO HOST
# ==============================================================================
echo "[*] Pulling trace artifact to host..."
adb pull "${TRACE_OUTPUT_DEVICE}" "${TRACE_OUTPUT_HOST}"
adb shell rm -f "${TRACE_OUTPUT_DEVICE}"

echo "[+] Trace saved to: ${TRACE_OUTPUT_HOST}"

# ==============================================================================
# STEP 4: HOW TO LOAD & INSPECT IN UI.PERFETTO.DEV
# ==============================================================================
# 1. Open Google Chrome and navigate to: https://ui.perfetto.dev
# 2. In the top-left sidebar, click "Open trace file" (or drag & drop trace.perfetto-trace)
# 3. Locate your Android app:
#    - Press "/" on your keyboard to open the search bar.
#    - Search for your package name: ${APP_PACKAGE}
# 4. Analyze App & Thread Tracks:
#    - Expand your process to view the Main/UI thread and RenderThread.
#    - Inspect custom spans generated by androidx.tracing (Trace.beginSection).
#    - Check frame slices under "Actual Timeline" for jank or missed VSYNC deadlines (>16ms / >8ms).
#    - Green bars = Running on CPU core
#    - Blue bars  = Runnable (waiting in CPU run-queue / thread contention)
#    - Brown bars = Sleeping (blocked on IPC/binder, choreographer, or lock contention)